development/flocker/config/routes.rb
Flockr::Application.routes.draw do
  get "comments/new"
  get "comments/create"
  get "comments/destroy"
  get "comments/edit"
  root 'home#index'

  resources :sessions, only: %i[new create destroy]
  get '/sign_up' => 'users#new'
  get '/sign_in' => 'sessions#new'
  delete '/sign_out' => 'sessions#destroy'

  resources :users do
    resources :photos do
      resources :comments, only: %i[new create edit update destroy]
    end
  end

end

development/flocker/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
  validates_presence_of :body, :user, :photo
end

development/flocker/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_photo
  before_action :set_user

  def new
    @comment = @photo.comments.new
  end

  def create
    params_with_user = comment_params.merge(user: @user)
    @comment = @photo.comments.new(params_with_user)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to [@user, @photo], notice: 'Comment was successfully added.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html do
          flash.now[:alert] = @comment.errors.full_messages
          render action: 'new'
        end
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @comment = @photo.comments.find(params[:id])
  end

  def update
    @comment = @photo.comments.find(params[:id])

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to user_photo_path(@user, @photo), notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy

    respond_to do |format|
      format.html { redirect_to user_photo_url(@user, @photo) }
      format.json { head :no_content }
    end
  end

  private

  def set_photo
    @photo = Photo.find(params[:photo_id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

development/flocker/app/helpers/comments_helper.rb
module CommentsHelper
end

development/flocker/app/views/comments/_comment.html.erb
<tr>
  <td>
    <p class="text-muted">
      <%= time_ago_in_words(comment.updated_at) %> ago,
      <span class="label label-<%= %w[default primary success info].sample %>">
        <%= comment.user.username -%>
      </span>
      said:
    </p>

    <blockquote>
      <%= comment.body %>
    </blockquote>
  </td>

  <% if current_user == comment.user %>
      <td>
        <%= link_to 'Edit', edit_user_photo_comment_path(current_user, @photo, comment), class: 'btn btn-warning btn-xs' %>
        <%= link_to 'Delete', user_photo_comment_path(current_user, @photo, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
      </td>
  <% end %>
</tr>

development/flocker/app/views/comments/_form.html.erb
<%= form_for(comment, url: user_photo_comment_path(user, photo, comment), html: { mulitpart: true, role: 'form' }) do |f| %>
    <% if comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(comment.errors.count, 'error') %> prohibited this comment from being saved:</h2>

          <ul>
            <% comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :body %><br>
      <%= f.text_area :body, class: 'form-control', rows: 3 %>
    </div>

    <div class="actions">
      <%= f.submit 'Add Comment', class: 'btn btn-primary' %>
    </div>
<% end %>

development/flocker/app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<div class="row">
  <div class="col-md-6">
    <p>Comment for <%= @photo.user.username %>'s Photo "<%= @photo.file_name %>"</p>

    <%= render 'form', user: @user, photo: @photo, comment: @comment %>

    <%= link_to user_photo_path(@user, @photo) do %>
        <button type="button" class="btn btn-default btn-xs">
          <span class="glyphicon glyphicon-backward"></span>
          Back
        </button>
    <% end %>
  </div>
</div>

development/flocker/app/views/comments/new.html.erb
<h1>New Comment</h1>

<div class="row">
  <div class="col-md-6">
    <p>Comment for <%= @photo.user.username %>'s Photo "<%= @photo.file_name %>"</p>

    <%= render 'form', user: @user, photo: @photo, comment: @comment %>

    <%= link_to user_photo_path(@user, @photo) do %>
        <button type="button" class="btn btn-default btn-xs">
          <span class="glyphicon glyphicon-backward"></span>
          Back
        </button>
    <% end %>
  </div>
</div>