development/flocker/config/routes.rb
Flockr::Application.routes.draw do
  get "comments/new"
  get "comments/create"
  get "comments/destroy"
  get "comments/edit"
  root 'home#index'

  resources :sessions, only: %i[new create destroy]
  get '/sign_up' => 'users#new'
  get '/sign_in' => 'sessions#new'
  delete '/sign_out' => 'sessions#destroy'

  resources :users do
    resources :photos do
      resources :comments, only: %i[new create edit update destroy]
    end
  end

end

development/flocker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flockr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="navbar navbar-default">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="/">Flockr</a>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% if request.path == users_path %>
            <li class="active"><%= link_to 'Users', users_path%></li>
        <% else %>
            <li><%= link_to 'Users', users_path%></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li><%= link_to 'Sign Out', sign_out_path, method: :delete %></li>
        <% else %>
            <% if request.path == sign_up_path %>
                <li class="active"><%= link_to 'Sign Up', sign_up_path %></li>
            <% else %>
                <li><%= link_to 'Sign Up', sign_up_path %></li>
            <% end %>

            <% if request.path == sign_in_path %>
                <li class="active"><%= link_to 'Sign In', sign_in_path %></li>
            <% else %>
                <li><%= link_to 'Sign In', sign_in_path %></li>
            <% end %>
        <% end %>
      </ul>
    </div>
  </div>

  <%= yield %>
</div>

</body>
</html>