development/flocker/config/routes.rb
Flockr::Application.routes.draw do
  get "comments/new"
  get "comments/create"
  get "comments/destroy"
  get "comments/edit"
  root 'home#index'

  resources :sessions, only: %i[new create destroy]
  get '/sign_up' => 'users#new'
  get '/sign_in' => 'sessions#new'
  delete '/sign_out' => 'sessions#destroy'

  resources :users do
    resources :photos do
      resources :comments, only: %i[new create edit update destroy]
    end
  end

end

development/flocker/app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader

  validates_presence_of :file_name
end

development/flocker/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /photos
  # GET /photos.json
  def index
    respond_to do |format|
      format.html { redirect_to user_path(@user) }
      format.json { render json: @user.photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = @user.photos.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = @user.photos.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to user_photo_path(@user, @photo), notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to user_photo_path(@user, @photo), notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to user_photos_url(@user) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:file_name, :path, :user_id, :image)
    end
end

development/flocker/app/helpers/photos_helper.rb
module PhotosHelper
end

development/flocker/app/views/photos/_form.html.erb
<%= form_for(@photo, url: user_photo_path(@user, @photo), html: { mulitpart: true, role: 'form' }) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, 'error') %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :file_name %><br>
    <%= f.text_field :file_name, class: 'form-control' %>
  </div>

    <% if @photo.image? %>
        <div class="form-group">
          <%= image_tag(@photo.image_url(:thumb), class: 'img-thumbnail') if @photo.image? %>
        </div>
    <% end %>

  <div class="form-group">
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Add Photo', class: 'btn btn-primary' %>
  </div>
<% end %>

development/flocker/app/views/photos/_index.html.erb
<h3>Photos</h3>

<table class="table">
  <thead>
    <tr>
      <th>File name</th>
      <th>Photo</th>
      <% if current_user == user %>
          <th></th>
          <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% user.photos.each do |photo| %>
      <tr>
        <td><%= link_to photo.file_name, user_photo_path(user, photo), class: 'btn btn-link' %></td>
        <td><%= link_to (image_tag(photo.image_url(:thumb), class: 'img-thumbnail')), user_photo_path(user, photo) %></td>
        <% if current_user == user %>
            <td><%= link_to 'Edit', edit_user_photo_path(user, photo), class: 'btn: btn-warning btn-xs' %></td>
            <td><%= link_to 'Destroy', user_photo_path(user, photo), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<hr/>

<%= link_to 'New Photo', new_user_photo_path(user), class: 'btn btn-primary pull-right' %>

development/flocker/app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>

    <%= link_to 'Show', user_photo_path(@user, @photo) %> |
    <%= link_to 'Back', user_photos_path(@user) %>
  </div>
</div>

development/flocker/app/views/photos/new.html.erb
<h1>New photo</h1>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>

    <%= link_to 'Back', user_photos_path(@user) %>
  </div>
</div>

development/flocker/app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <div class="jumbotron">
      <p>
        <%= image_tag(@photo.image_url(:default_view)) %>
      </p>

      <hr/>

      <p>
        <%= link_to 'View original', @photo.image_url, class: 'pull-right' %>
      </p>

      <p>
        <h3><%= @photo.file_name %></h3>
      </p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3>Comments</h3>
    <hr/>

    <% if @photo.comments.empty? %>
        <p>No comments.</p>
    <% else %>
        <table class="table">
          <% @photo.comments.each do |comment| %>
              <%= render partial: comment %>
          <% end %>
        </table>
    <% end %>
    <p>
      <%= link_to 'Leave a comment!', new_user_photo_comment_path(current_user, @photo) %>
    </p>
  </div>
</div>

<hr/>

<div class="row">
  <div class="col-md-12">
    <% if current_user == @user %>
        <%= link_to edit_user_photo_path(@user, @photo) do %>
            <button type="button" class="btn btn-info btn-xs">
              <span class="glyphicon glyphicon-cog"></span>
              Edit
            </button>
        <% end %>
    <% end %>
    <%= link_to user_photos_path(@user) do %>
        <button type="button" class="btn btn-default btn-xs">
          <span class="glyphicon glyphicon-backward"></span>
          Back
        </button>
    <% end %>
  </div>
</div>